version: "3.8"

services:
  # Setup portainer
  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
  # Promethues Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    #networks:
      #- networkpotoromonitoring

  # Grafana Service
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini # To enable iframe html
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    #networks:
      #- networkpotoromonitoring

  # Node Exporter
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  
  # Cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped

  # Elastic Search
  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    restart: unless-stopped
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/datafile
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastcinetwork

  # Kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.1
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastcinetwork
  
  # Back End

  # Api gateway 1
  api-gateway:
    container_name: api-gateway
    image: huynx11/potoro-be-api-gateway:latest
    restart: unless-stopped
    ports:
      - "5221:80"

  # Identity service 2
  identity-service:
    container_name: identity-service
    image: huynx11/potoro-be-identity-service:latest
    restart: unless-stopped
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings_DefaultConnection=<YOUR_CONNECTION_STRING>
    ports:
      - "5220:80"
  
  # Booking service 3
  booking-service:
    container_name: booking-service
    image: huynx11/potoro-be-booking-service:latest
    restart: unless-stopped
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings_DefaultConnection=<YOUR_CONNECTION_STRING>
    ports:
      - "5222:80"

  # Envoice service 4
  envoice-service:
    container_name: envoice-service
    image: huynx11/potoro-be-envoice-service:latest
    restart: unless-stopped
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings_DefaultConnection=<YOUR_CONNECTION_STRING>
    ports:
      - "5224:80"

  # Facility 5
  facility-service:
    container_name: facility-service
    image: huynx11/potoro-be-facility-service:latest
    restart: unless-stopped
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings_DefaultConnection=<YOUR_CONNECTION_STRING>
    ports:
      - "5223:80"

  # Payment 6
  payment-service:
    container_name: payment-service
    image: huynx11/potoro-be-payment-service:latest
    restart: unless-stopped
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings_DefaultConnection=<YOUR_CONNECTION_STRING>
    ports:
      - "5225:80"

  # Front End

  # user
  front-end-user:
    container_name: front-end-user
    image: huynx11/potoro-fe-user:latest
    restart: unless-stopped
    ports:
      - "5599:80"
    depends_on:
      - identity-service
      - booking-service
      - facility-service
      - envoice-service
      - payment-service
      - search-service
  
  # admin
  front-end-admin:
    container_name: front-end-admin
    image: huynx11/potoro-fe-admin:latest
    restart: unless-stopped
    ports:
      - "5598:80"
    depends_on:
      - identity-service
      - booking-service
      - facility-service
      - envoice-service
      - payment-service
      - search-service

networks:
  elastcinetwork:
    driver: bridge

volumes:
  portainer-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  elasticsearch-data: